// import { Inter } from "next/font/google";
// import "./globals.css";
// import { NextIntlClientProvider } from 'next-intl';


// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// export default function RootLayout({ children,params }) {
//   const { locale } = params;
//   const messages = require(`../../../messages/${locale}.json`);
//   // const messages = require(`../../../messages`);
//   return (
//     <html lang={locale}>
//     <head>
//     <link rel="preconnect" href="https://fonts.googleapis.com"/>
// <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
// <link href="https://fonts.googleapis.com/css2?family=Ropa+Sans:ital@0;1&display=swap" rel="stylesheet"/>
//     </head>
//     <NextIntlClientProvider locale={locale} messages={messages}>
//       <body className={inter.className}>{children}</body>
//       </NextIntlClientProvider>
//       {/* <body className={inter.className}>{children}</body> */}
//     </html>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loadMessages(locale) {
  try {
    // const messages = await import(`../../../messages/${locale}.json`);
    const messages = await import(`@/messages/${locale}.json`);
    return messages.default;
  } catch (error) {
    notFound();
  }
}

export default async function RootLayout({ children, params }) {
  const { locale } = params;
  console.log("🚀 ~ RootLayout ~ locale:", locale)
  const messages = await loadMessages(locale);

  return (
    <html lang={locale}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Ropa+Sans:ital@0;1&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
